version: '2.1'

services:
    db:
        image: mongo
        restart: always
        networks:
            - default
        ports:
            - '27017:27017'
    api:
        image: thiagojsimaome/ita-node-api:finalyVersion
        restart: always
        networks:
            - default
        depends_on:
            - db
        ports:
            - '3000:3000'
        command: yarn dev
        volumes:
            - .:/usr/app
