version: '2.1'

services:
    db:
        image: mongo
        restart: always
        ports:
            - '27017:27017'
    api:
        image: thiago-js/node-api
        restart: always
        depends_on:
            - db
        ports:
            - '3000:3000'
        command: yarn dev
        volumes:
            - .:/usr/app
